name: datasets
channels:
  - defaults
  - pytorch
dependencies:
  - numpy
  - pandas
  - pip=20
  - python=3.8
  - pytorch=1.4.*
  - scipy
  - pip:
      - hydra-core==1.0.6
      - mne
      - torchaudio==0.4.0
