channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - h5py
  - cudnn
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pillow
  - pip
  - python=3.8
  - pytorch=1.8.1
  - pytorch-cuda
  - scipy
  - torchvision=0.9.1
  - h5py
  - pip:
      - autopep8
      - hydra-core
      - mne
      - pylint
      - pytest
      - pytorch-lightning==1.2.10
      - pytorch-lightning-bolts==0.3.2
      - pyyaml
      - scikit-learn
      - seaborn
      - statsmodels
      - tensorboard
      - wandb
      - pingouin
      - torchmetrics==0.2.0
